version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: tasued_user
      POSTGRES_PASSWORD: DTcUq9BCr3j4TZLE0wF7edPK4ldAWl2T
      POSTGRES_DB: tasued
    ports:
      - '5432:5432'
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: env("DATABASE_URL")
    depends_on:
      - postgres

volumes:
  postgres_data: